// angular/showcase/src/app/components/protected/grid-tabulator-client-datasource/grid-tabulator-client-datasource.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ViewChild,
  Input,
  OnChanges,
  SimpleChanges,
  AfterViewInit,
  OnDestroy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DatasourceDefaults } from '@genesislcap/foundation-comms';
import { STATE_CHANGER_CONFIG } from '../../../config';
import {
  setComponentItemsMap,
  getElementByTagFromComponent,
} from '../../../utils/goldenLayout.helper';
import { LayoutEmitEvents } from '@genesislcap/foundation-layout';
import { LayoutComponentsNames } from './grid-tabulator-client-datasource.types';
@Component({
  selector: 'app-grid-tabulator-client-datasource',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './grid-tabulator-client-datasource.component.html',
  styleUrl: './grid-tabulator-client-datasource.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GridTabulatorClientDatasourceComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('gridLayout') gridLayoutElement!: any;

  @Input() resourceName: string = STATE_CHANGER_CONFIG.DEFAULT_RESOURCE_NAME;
  @Input() criteria: string = STATE_CHANGER_CONFIG.DEFAULT_CRITERIA;

  layoutComponentsMap: Map<LayoutComponentsNames, any> = new Map();
  maxView = DatasourceDefaults.MAX_VIEW_1000;
  maxRows = DatasourceDefaults.MAX_ROWS_250;
  restartOnReconnection = true;
  ready = false;
  listeners: (() => void)[] = [];

  setReady() {
    this.ready = true;
  }

  ngAfterViewInit() {
    try {
      setComponentItemsMap(this.gridLayoutElement.nativeElement, this.layoutComponentsMap);
    } catch (e) {
      console.error(e);
    }

    const listener = this.setReady.bind(this);
    this.listeners.push(listener);
    this.gridLayoutElement.nativeElement.addEventListener(LayoutEmitEvents.firstLoaded, listener);
  }

  ngOnChanges(changes: SimpleChanges) {
    if (!changes['resourceName'] && !changes['criteria'] && !this.ready) {
      return;
    }

    if (this.layoutComponentsMap.size > 0) {
      this.layoutComponentsMap.forEach((component: any) => {
        const datasource = getElementByTagFromComponent(
          component,
          'grid-tabulator-client-side-datasource',
        );

        if (changes['resourceName']) {
          datasource.resourceName = changes['resourceName'].currentValue;
        }

        if (changes['criteria']) {
          datasource.criteria = changes['criteria'].currentValue;
        }
      });
    }
  }

  ngOnDestroy() {
    this.listeners.forEach((listener) => {
      this.gridLayoutElement.nativeElement.removeEventListener(
        LayoutEmitEvents.firstLoaded,
        listener,
      );
    });
  }
}

<zero-layout>
  <zero-layout-region type="vertical">
    <zero-layout-region>
      <zero-layout-item title="(stream)" closable>
        <zero-grid-tabulator
          #dataSource1test
          persist-column-state-key="grid-tabulator-simple-column-state"
        >
          <grid-tabulator-client-side-datasource
            #dataSource1
            resource-name="ALL_COUNTERPARTYS"
            [attr.criteria]="criteria"
            [attr.is-snapshot]="false"
            [attr.max-rows]="maxRows"
            [attr.max-view]="maxView"
            [attr.reverse]="false"
            [attr.restart-on-reconnection]="true"
          ></grid-tabulator-client-side-datasource>
        </zero-grid-tabulator>
      </zero-layout-item>

      <zero-layout-item title="(snapshot)" closable>
        <zero-grid-tabulator persist-column-state-key="grid-tabulator-simple-column-state">
          <grid-tabulator-client-side-datasource
            #dataSource2
            resource-name="ALL_COUNTERPARTYS"
            [attr.criteria]="criteria"
            is-snapshot="true"
            [attr.max-rows]="maxRows"
            [attr.max-view]="maxView"
            [attr.reverse]="false"
            [attr.restart-on-reconnection]="true"
          ></grid-tabulator-client-side-datasource>
        </zero-grid-tabulator>
      </zero-layout-item>
    </zero-layout-region>
  </zero-layout-region>
</zero-layout>

// react/showcase/src/components/protected/GridTabulatorClientDatasource/GridTabulatorClientDatasource.tsx
import { useRef, useEffect, useContext } from 'react';
import { DatasourceDefaults } from '@genesislcap/foundation-comms';
import { FoundationLayout } from '@genesislcap/foundation-layout';
import { LayoutComponentsNames } from './GridTabulatorClientDatasource.types';
import StateChangerContext from '../../../store/StateChanger/StateChangerContext';
import {
  setComponentItemsMap,
  getElementByTagFromComponent,
} from '../../../utils/goldenLayout.helper';

const GridTabulatorClientDatasource = () => {
  const stateChangerContext = useContext(StateChangerContext);
  if (!stateChangerContext) {
    throw new Error('StateChangerContext is not defined');
  }
  const { state: stateChangerState } = stateChangerContext;
  const layoutComponentsMap: Map<LayoutComponentsNames, any> = new Map();
  const gridLayout = useRef<FoundationLayout | null>(null);
  const maxView = DatasourceDefaults.MAX_VIEW_1000;
  const maxRows = DatasourceDefaults.MAX_ROWS_250;
  const restartOnReconnection = true;

  useEffect(() => {
    if (gridLayout.current) {
      setComponentItemsMap(gridLayout.current, layoutComponentsMap);
    }
  }, []);

  useEffect(() => {
    if (gridLayout.current) {
      layoutComponentsMap.forEach((component: any) => {
        const datasource = getElementByTagFromComponent(
          component,
          'grid-tabulator-client-side-datasource',
        );

        if (stateChangerState.resourceName) {
          datasource.resourceName = stateChangerState.resourceName;
        }

        if (stateChangerState.criteria) {
          datasource.criteria = stateChangerState.criteria;
        }
      });
    }
  }, [stateChangerState]);

  return (
    <zero-layout ref={gridLayout}>
      <zero-layout-region type="vertical">
        <zero-layout-region>
          <zero-layout-item title="(stream)" closable>
            <zero-grid-tabulator
              registration="stream"
              persist-column-state-key="grid-tabulator-simple-column-state"
            >
              <grid-tabulator-client-side-datasource
                resource-name={stateChangerState.resourceName}
                criteria={stateChangerState.criteria}
                is-snapshot={false}
                max-rows={maxRows}
                max-view={maxView}
                reverse={false}
                restart-on-reconnection={restartOnReconnection}
              ></grid-tabulator-client-side-datasource>
            </zero-grid-tabulator>
          </zero-layout-item>
          <zero-layout-item registration="snapshot" title="(snapshot)" closable>
            <zero-grid-tabulator persist-column-state-key="grid-tabulator-simple-column-state">
              <grid-tabulator-client-side-datasource
                resource-name={stateChangerState.resourceName}
                criteria={stateChangerState.criteria}
                is-snapshot={true}
                max-rows={maxRows}
                max-view={maxView}
                reverse={false}
                restart-on-reconnection={restartOnReconnection}
              ></grid-tabulator-client-side-datasource>
            </zero-grid-tabulator>
          </zero-layout-item>
        </zero-layout-region>
      </zero-layout-region>
    </zero-layout>
  );
};

export default GridTabulatorClientDatasource;
