// react/showcase/src/guards/AuthGuard.tsx
import React, { ReactNode } from 'react';
import { Navigate } from 'react-router-dom';
import { authService } from '../services/auth.service';

interface AuthGuardProps {
  children: ReactNode;
}

const AuthGuard: React.FC<AuthGuardProps> = ({ children }) => {
  const isAuthorized = authService.isUserAuthenticated(); 

  if (!isAuthorized) {
    return <Navigate to="/auth" />;
  }

  return <>{children}</>;
};

export default AuthGuard;

// angular/blank-app-seed/src/app/guards/auth.guard.ts
import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';
import { AUTH_PATH } from '../app.routes';
import { AuthService } from '../services/auth.service';


@Injectable({
  providedIn: 'root',
})
export class AuthGuard implements CanActivate {
  constructor(
    private authService: AuthService,
    private router: Router,
  ) {}

  async canActivate(): Promise<boolean> {
    const isUserAuthenticated = await this.authService.isUserAuthenticated();

    if (!isUserAuthenticated) {
      this.router.navigate([`/${AUTH_PATH}`]);
      return false;
    }
    return true;
  }
}
