// angular/alpha-angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
  imports: [
      // ...
      FormsModule,
      // ...
  ],
})
export class AppComponent {
  title = 'alpha-angular';
  
  exampleTextField = '';

  onClick() {
    console.log(this.exampleTextField);
  }
}
<alpha-card>
  <h2>{{title}}</h2>
  <alpha-text-field [(ngModel)]="exampleTextField" name="exampleTextField" ngDefaultControl placeholder="Enter Some Text"></alpha-text-field>
  <alpha-button appearance="accent" (click)="onClick()">Click Me</alpha-button>
</alpha-card>

// react/alpha-react/src/App.js
import './App.css';
import { useState } from 'react';
import { useCustomEventListener } from './hooks/useCustomEventListener';
import { 
  provideDesignSystem, 
  alphaCard, 
  alphaButton,
  alphaTextField
} from '@genesislcap/alpha-design-system';

provideDesignSystem()
    .register(
        alphaCard(),
        alphaButton(),
        alphaTextField()
    );


function App() {
  const [value, setValue] = useState('');
  const webComponentRef = useCustomEventListener('input', (event) => {
    setValue(event.target.value);
  });

  return (
    <alpha-card>
      <h2>Genesis Foundation React</h2>
      <alpha-text-field name='exampleTextField' placeholder="Enter Some Text" ref={webComponentRef}></alpha-text-field>
      <alpha-button appearance="accent" onClick={() => console.log(value)}>Click Me</alpha-button>
  </alpha-card>
  );
}

export default App;
