// angular/showcase/src/app/components/protected/grid-pro-server-datasource/grid-pro-server-datasource.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DatasourceDefaults } from '@genesislcap/foundation-comms';

@Component({
  selector: 'app-grid-pro-server-datasource',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './grid-pro-server-datasource.component.html',
  styleUrl: './grid-pro-server-datasource.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GridProServerDatasourceComponent {
  criteria?: string = 'NAME != null';
  maxRows = 15;
  maxView = DatasourceDefaults.MAX_VIEW_1000;
  resourceName = 'ALL_COUNTERPARTYS';
  reverse = false;
  pagination = false;
}

<div class="top-area">
  <p style="text-align: center; align-self: center">
    Infinite Scrolling - VERY EXPERIMENTAL {{ resourceName }}
  </p>
</div>
<zero-grid-pro
  style="display: block; height: 450px"
  persist-column-state-key="grid-pro-ssrm-column-state"
>
  <grid-pro-server-side-datasource
    [attr.criteria]="criteria"
    [attr.max-rows]="maxRows"
    [attr.max-view]="maxView"
    [attr.resource-name]="resourceName"
    [attr.reverse]="reverse"
    [attr.pagination]="pagination"
  ></grid-pro-server-side-datasource>
</zero-grid-pro>
<div class="top-area">
  <p style="text-align: center; align-self: center">Pagination - VERY EXPERIMENTAL</p>
</div>
<zero-grid-pro
  style="display: block; height: 450px"
  persist-column-state-key="grid-pro-ssrm-column-state"
>
  <grid-pro-server-side-datasource
    [attr.criteria]="criteria"
    [attr.max-rows]="maxRows"
    [attr.max-view]="maxView"
    [attr.resource-name]="resourceName"
    [attr.reverse]="reverse"
    [attr.pagination]="pagination"
  ></grid-pro-server-side-datasource>
</zero-grid-pro>

// react/showcase/src/components/protected/GridProServerDatasource/GridProServerDatasource.tsx
import { useEffect, useContext } from 'react';
import { DatasourceDefaults } from '@genesislcap/foundation-comms';
import StateChangerContext from '../../../store/StateChanger/StateChangerContext';

const GridProServerDatasource = () => {
  const stateChangerContext = useContext(StateChangerContext);
  if (!stateChangerContext) {
    throw new Error('StateChangerContext is not defined');
  }
  const { state: stateChangerState } = stateChangerContext;
  const maxRows = 15;
  const maxView = DatasourceDefaults.MAX_VIEW_1000;
  const reverse = false;
  const pagination = false;

  useEffect(() => {}, []);

  return (
    <section>
      <div className="top-area">
        <p style={{ textAlign: 'center', alignSelf: 'center' }}>
          Infinite Scrolling - VERY EXPERIMENTAL
        </p>
      </div>
      <zero-grid-pro
        style={{ display: 'block', height: '450px' }}
        persist-column-state-key="grid-pro-ssrm-column-state"
      >
        <grid-pro-server-side-datasource
          resource-name={stateChangerState.resourceName}
          criteria={stateChangerState.criteria}
          max-rows={maxRows}
          max-view={maxView}
          reverse={reverse}
          pagination={pagination}
        ></grid-pro-server-side-datasource>
      </zero-grid-pro>
      <div className="top-area">
        <p style={{ textAlign: 'center', alignSelf: 'center' }}>
          Pagination - VERY EXPERIMENTAL
        </p>
      </div>
      <zero-grid-pro
        style={{ display: 'block', height: '450px' }}
        persist-column-state-key="grid-pro-ssrm-column-state"
      >
        <grid-pro-server-side-datasource
          resource-name={stateChangerState.resourceName}
          criteria={stateChangerState.criteria}
          max-rows={maxRows}
          max-view={maxView}
          reverse={reverse}
          pagination={pagination}
        ></grid-pro-server-side-datasource>
      </zero-grid-pro>
    </section>
  );
};

export default GridProServerDatasource;
