// angular/showcase/src/app/components/protected/grid-pro-client-datasource-linked/grid-pro-client-datasource-linked.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ViewChild,
  AfterViewInit,
  OnDestroy,
} from '@angular/core';
import { GridOptions, RowSelectedEvent } from '@ag-grid-community/core';
import { CommonModule } from '@angular/common';
import { LayoutEmitEvents } from '@genesislcap/foundation-layout';
import { LayoutComponentsNames } from './grid-pro-client-datasource-linked.types';
import {
  setComponentItemsMap,
  getElementByTagFromComponent,
} from '../../../utils/goldenLayout.helper';

const DATASOURCE_ELEMENT_TAG = 'grid-pro-genesis-datasource';

@Component({
  selector: 'app-grid-pro-client-datasource-linked',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './grid-pro-client-datasource-linked.component.html',
  styleUrl: './grid-pro-client-datasource-linked.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GridProClientDatasourceLinkedComponent implements AfterViewInit, OnDestroy {
  @ViewChild('gridLayout') gridLayoutElement!: any;

  layoutComponentsMap: Map<LayoutComponentsNames, any> = new Map();
  deferredGridOptions: GridOptions = {
    rowSelection: 'single',
    onRowClicked: (e: RowSelectedEvent) => {
      this.instrumentName = e.node.isSelected() ? e.data?.INSTRUMENT_NAME : undefined;
    },
  };
  criteria?: string;
  private _instrumentName: any;
  set instrumentName(value: any) {
    this._instrumentName = value;

    const criteria = value ? `INSTRUMENT_NAME == '${value}'` : undefined;
    const allTradesComponent = this.layoutComponentsMap.get(LayoutComponentsNames.ALL_TRADES);
    const datasourceElement = getElementByTagFromComponent(
      allTradesComponent,
      DATASOURCE_ELEMENT_TAG,
    );
    datasourceElement.criteria = criteria;
  }
  get instrumentName(): any {
    return this._instrumentName;
  }

  setDeferredGridOptions = () => {
    const allPositions = this.layoutComponentsMap.get(LayoutComponentsNames.ALL_POSITIONS);
    const datasourceElement = getElementByTagFromComponent(allPositions, DATASOURCE_ELEMENT_TAG);

    datasourceElement.deferredGridOptions = this.deferredGridOptions;
  };

  ngAfterViewInit() {
    setComponentItemsMap(this.gridLayoutElement.nativeElement, this.layoutComponentsMap);

    this.gridLayoutElement.nativeElement.addEventListener(
      LayoutEmitEvents.firstLoaded,
      this.setDeferredGridOptions,
    );
  }

  ngOnDestroy() {
    this.gridLayoutElement?.nativeElement.removeEventListener('click', this.setDeferredGridOptions);
  }
}

<zero-layout #gridLayout>
  <zero-layout-region type="horizontal">
    <zero-layout-region>
      <zero-layout-item title="(ALL_POSITIONS)" registration="all-positions">
        <zero-grid-pro>
          <grid-pro-genesis-datasource resource-name="ALL_POSITIONS" [criteria]="criteria"></grid-pro-genesis-datasource>
        </zero-grid-pro>
      </zero-layout-item>
    </zero-layout-region>
    <zero-layout-region>
      <zero-layout-item title="(ALL_TRADES)" registration="all-trades">
        <zero-grid-pro>
          <grid-pro-genesis-datasource resource-name="ALL_TRADES" [criteria]="criteria"></grid-pro-genesis-datasource>
        </zero-grid-pro>
      </zero-layout-item>
    </zero-layout-region>
  </zero-layout-region>
</zero-layout>

// react/showcase/src/components/protected/GridProClientDatasourceLinked/GridProClientDatasourceLinked.tsx
import { useRef, useEffect } from 'react';
import { GridOptions, RowSelectedEvent } from '@ag-grid-community/core';
import {
  LayoutEmitEvents,
  FoundationLayout,
} from '@genesislcap/foundation-layout';
import { LayoutComponentsNames } from './GridProClientDatasourceLinked.types';
import {
  setComponentItemsMap,
  getElementByTagFromComponent,
} from '../../../utils/goldenLayout.helper';

const DATASOURCE_ELEMENT_TAG = 'grid-pro-genesis-datasource';

const GridProClientDatasourceLinked = () => {
  const layoutComponentsMap: Map<LayoutComponentsNames, any> = new Map();
  const deferredGridOptions: GridOptions = {
    rowSelection: 'single',
    onRowClicked: (e: RowSelectedEvent) => {
      const instrumentName = e.node.isSelected()
        ? e.data?.INSTRUMENT_NAME
        : undefined;
      if (instrumentName) {
        const allTradesComponent = layoutComponentsMap.get(
          LayoutComponentsNames.ALL_TRADES,
        );
        const datasourceElement = getElementByTagFromComponent(
          allTradesComponent,
          DATASOURCE_ELEMENT_TAG,
        );
        datasourceElement.criteria = `INSTRUMENT_NAME == '${instrumentName}'`;
      }
    },
  };
  const gridLayout = useRef<FoundationLayout | null>(null);

  useEffect(() => {
    if (gridLayout.current) {
      setComponentItemsMap(gridLayout.current, layoutComponentsMap);

      const handleGridLayoutFirstLoaded = () => {
        const allPositions = layoutComponentsMap.get(
          LayoutComponentsNames.ALL_POSITIONS,
        );
        const datasourceElement = getElementByTagFromComponent(
          allPositions,
          DATASOURCE_ELEMENT_TAG,
        );

        datasourceElement.deferredGridOptions = deferredGridOptions;
      };

      gridLayout.current.addEventListener(
        LayoutEmitEvents.firstLoaded,
        handleGridLayoutFirstLoaded,
      );

      return () => {
        gridLayout.current?.removeEventListener(
          LayoutEmitEvents.firstLoaded,
          handleGridLayoutFirstLoaded,
        );
      };
    }
  }, []);

  return (
    <zero-layout ref={gridLayout}>
      <zero-layout-region type="horizontal">
        <zero-layout-region>
          <zero-layout-item
            title="(ALL_POSITIONS)"
            registration="all-positions"
          >
            <zero-grid-pro>
              <grid-pro-genesis-datasource resource-name="ALL_POSITIONS"></grid-pro-genesis-datasource>
            </zero-grid-pro>
          </zero-layout-item>
        </zero-layout-region>
        <zero-layout-region>
          <zero-layout-item title="(ALL_TRADES)" registration="all-trades">
            <zero-grid-pro>
              <grid-pro-genesis-datasource resource-name="ALL_TRADES"></grid-pro-genesis-datasource>
            </zero-grid-pro>
          </zero-layout-item>
        </zero-layout-region>
      </zero-layout-region>
    </zero-layout>
  );
};

export default GridProClientDatasourceLinked;
