// angular/basic/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'Genesis Foundation Angular';

  exampleTextField = '';

  onClick() {
    console.log(this.exampleTextField);
  }
}

<alpha-card>
  <h2>{{ title }}</h2>
  <alpha-text-field
    [(ngModel)]="exampleTextField"
    name="exampleTextField"
    ngDefaultControl
    placeholder="Enter Some Text"
  ></alpha-text-field>
  <alpha-button appearance="accent" (click)="onClick()">Click Me</alpha-button>
</alpha-card>

// react-19/rapid/src/App.js
import './App.css';
import React, { useState } from 'react';
import { 
  provideDesignSystem, 
  rapidCard, 
  rapidButton,
  rapidTextField,
  rapidCheckbox,
} from '@genesislcap/rapid-design-system';

provideDesignSystem()
  .register(
    rapidCard(),
    rapidButton(),
    rapidTextField(),
    rapidCheckbox()
  );


function App() {
  // State to hold the input value
  const [inputValue, setInputValue] = useState('');
  const [checkboxValue, setCheckboxState] = useState(false);

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  const handleCheckboxChange = (event) => {
    setCheckboxState(!!event.target.checked);
  };

  return (
    <rapid-card>
      <h2>Genesis Foundation React</h2>
      <p>input value: {inputValue} / checkbox value: {checkboxValue ? 'true' : 'false'}</p>
      <div style={{ padding: '10px', display: 'flex', 'justify-content': 'space-between', 'vertical-align': 'middle', 'align-items': 'center'}}>
      <rapid-text-field
        name='exampleTextField'
        placeholder="Enter Some Text"
        value={inputValue} 
        onInput={handleInputChange}
        style={{ 'margin': ' 0 50px 0 0' }}
      ></rapid-text-field>
      <rapid-checkbox onChange={handleCheckboxChange}></rapid-checkbox>
      </div>
      <rapid-button appearance="accent" onClick={() => console.log(inputValue)}>Click Me</rapid-button>
  </rapid-card>
  );
}

export default App;
